name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cargo-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install stable Rust
        run: |
          rustup toolchain install stable --profile minimal
          rustup default stable
      - name: Cargo check
        run: cargo check
